@startuml
'https://plantuml.com/class-diagram

Person <|-- ArrayList

class App{
    + readInput(inText: File): ArrayList<Person>
    + sortNames(database: ArrayList<Person>): ArrayList<Person>
    + formatInformation(database: ArrayList<Person>): String
}

class ArrayList {
Person[]: firstName, lastName
size()
}

class Person{
    - firstName: String
    - lastName: String

    <<constructor>> Person(firstName: String, lastName: String)
    + getFirstName(): String
    + setFirstName(first: String)
    + getLastName(): String
    + setLastName(last: Sting)
}


@enduml