@startuml
'https://plantuml.com/class-diagram

Person <|-- ArrayList

class App{
    + readInput(inText: File): ArrayList<Person>
    + createPerson(data: String): Person
    + formatInformation(database: ArrayList<Person>): String
}

class ArrayList {
Person[]: firstName, lastName, salary
size()
}

class Person{
    - firstName: String
    - lastName: String
    - salary: int

    <<constructor>> Person(firstName: String, lastName: String, salary: int)
    + getFirstName(): String
    + setFirstName(first: String)
    + getLastName(): String
    + setLastName(last: Sting)
    + getSalary(): int
    + setSalary(num: int)
}


@enduml