@startuml
'https://plantuml.com/class-diagram

ArrayList <|-- Site

class App{
    + getUserInput(): Site
    + createFile(Site info):
    + createMessage(Site info): String
}

class ArrayList {
Site[] elementData
size()
}

class Site{
    - siteName: String
    - author: String
    - javascript: boolean
    - css: boolean

    <<constructor>> FileInformation(siteName: String, author: String, javascript: boolean, css: boolean)
    + setSiteName(site: String)
    + getSiteName():String
    + setAuthor(author: String)
    + getAuthor(): String
    + setJavascript(java: boolean)
    + getJavascript(): boolean
    + setCSS(css: boolean)
    + getCSS(): boolean
}

@enduml