@startuml
'https://plantuml.com/class-diagram

class App{
    + searchInText(inText: File): String
    + getOutputFile():String
}

class WordFinder{
    - private searchWord: String
    - private changeWord: String

    <<constructor>> WordFinder(searchWord:String, changeWord:String)
    + getSearchWord(): String
    + getChangeWord(): String
}

@enduml